// Toppings Data that will appear in Details.jsx page

export const CheeseOptions = [
  {
    id: "ch1",
    name: "Normal Cheese",
    src: "/images/cheese/normalcheese.jpg",
    altText: "Normal Cheese",
    calorie: 200,
    addon: "0.00",
    value: "normal-cheese",
  },
  {
    id: "ch2",
    name: "Extra Cheese",
    src: "/images/cheese/extracheese.jpg",
    altText: "Extra Cheese",
    calorie: 250,
    addon: "1.00",
    value: "extra-cheese",
  },
  {
    id: "ch3",
    name: "Less Cheese",
    src: "/images/cheese/lesscheese.jpg",
    altText: "Less Cheese",
    calorie: 150,
    addon: "0.00",
    value: "less-cheese",
  },
  {
    id: "ch4",
    name: "Plant Cheese",
    src: "/images/cheese/plantcheese.jpg",
    altText: "Plant Cheese",
    calorie: 220,
    addon: "1.50",
    value: "plant-cheese",
  },
  {
    id: "ch5",
    name: "No Cheese",
    src: "/images/cheese/Nocheese.jpg",
    altText: "No Cheese",
    calorie: 0,
    addon: "0.00",
    value: "no-cheese",
  },
];

export const AdditionalMeatToppings = [
  {
    id: "mt1",
    name: "Pepperoni",
    src: "/images/Additional meat toppings/beef pepperoni.jpg",
    altText: "Pepperoni",
    calorie: 80,
    addon: "1.50",
  },
  {
    id: "mt2",
    name: "beef bacon",
    src: "/images/Additional meat toppings/beef bacon.jpg",
    altText: "Pepperoni",
    calorie: 60,
    addon: "1.50",
  },
  {
    id: "mt3",
    name: "beef",
    src: "/images/Additional meat toppings/beef.jpg",
    altText: "beef",
    calorie: 50,
    addon: "1.50",
  },

  {
    id: "mt4",
    name: "Pulled Chicken",
    src: "/images/Additional meat toppings/pulled chicken.jpg",
    altText: "Pulled Chicken",
    calorie: 80,
    addon: "1.50",
  },

  {
    id: "mt5",
    name: "Turkey Ham",
    src: "/images/Additional meat toppings/turkey ham.jpg",
    altText: "turkey ham",
    calorie: 110,
    addon: "1.50",
  },
];

export const AdditionalNonMeatToppings = [
  {
    id: "nmt1",
    name: "Black Olives",
    src: "/images/non-meat/black olives.jpg",
    altText: "Black Olives",
    calorie: 15,
    addon: "0.50",
  },
  {
    id: "nmt2",
    name: "dried chilli flakes",
    src: "/images/non-meat/dried chilli flakes.jpg",
    altText: "Dried Chilli Flakes",
    calorie: 30,
    addon: "0.50",
  },
  {
    id: "nmt3",
    name: "Fajita",
    src: "/images/non-meat/Fajita.jpg",
    altText: "Fajita",
    calorie: 25,
    addon: "0.50",
  },
  {
    id: "nmt4",
    name: "Goats Cheese",
    src: "/images/non-meat/goats cheese.jpg",
    altText: "Goats Cheese",
    calorie: 35,
    addon: "0.50",
  },
  {
    id: "nmt5",
    name: "Hot Honey",
    src: "/images/non-meat/hot honey.jpg",
    altText: "Hot Honey",
    calorie: 55,
    addon: "0.50",
  },
  {
    id: "nmt6",
    name: "Jalapenos",
    src: "/images/non-meat/jalapenos.jpg",
    altText: "Black Olives",
    calorie: 65,
    addon: "0.50",
  },
  {
    id: "nmt7",
    name: "Mixed Peppers",
    src: "/images/non-meat/mixed peppers.jpg",
    altText: "Mixed Peppers",
    calorie: 65,
    addon: "0.50",
  },
  {
    id: "nmt8",
    name: "Mushrooms",
    src: "/images/non-meat/mushrooms.jpg",
    altText: "Mushrooms",
    calorie: 65,
    addon: "0.50",
  },
  {
    id: "nmt9",
    name: "Pineapple",
    src: "/images/non-meat/pineapple.jpg",
    altText: "Pineapple",
    calorie: 65,
    addon: "0.50",
  },
  {
    id: "nmt10",
    name: "Red Onion",
    src: "/images/non-meat/red onion.jpg",
    altText: "Red Onion",
    calorie: 65,
    addon: "0.50",
  },
  {
    id: "nmt11",
    name: "Rouquito Pearl",
    src: "/images/non-meat/Rouquito pearl.jpg",
    altText: "Rouquito",
    calorie: 65,
    addon: "0.50",
  },
  {
    id: "nmt12",
    name: "Sweetcorn",
    src: "/images/non-meat/sweetcorn.jpg",
    altText: "sweetcorn",
    calorie: 65,
    addon: "0.50",
  },
];
